"""Discover the Karlsson parametrization's symmetry quotient numerically.

Invariant: moments of the Haagerup multiset {h_ij h_kl conj(h_il h_kj)}
(equivalence-invariant; moments rounded for hashing, full sorted multiset
compared on hash match). The campaign statement is also invariant under
conjugation/transpose, so those anti-equivalences count in the quotient.

Outputs: translation symmetries per axis (fine scans), surviving
candidate reflections, and the orbit size at generic points = the
campaign volume divisor."""

import itertools
import warnings

import numpy as np

from karlsson import karlsson_map

warnings.filterwarnings("ignore")


def haag(H):
    T = np.einsum("ij,kl,il,kj->ijkl", H, H, np.conj(H), np.conj(H))
    v = np.sort_complex(T.ravel().round(9))
    return v


def key(H):
    v = haag(H)
    return (round(float(np.abs(v).sum()), 6),
            round(float((np.abs(v) ** 2).sum()), 6),
            round(float(np.real(v).sum()), 6),
            round(float(np.abs(np.imag(v)).sum()), 6))


def same(H1, H2):
    return np.allclose(haag(H1), haag(H2), atol=1e-7)


def main():
    rng = np.random.default_rng(12)
    betas = [tuple(rng.uniform(0.3, 6.0, 3)) for _ in range(4)]

    # 1. translation symmetries per axis
    print("=== axis translation scans (step 2pi/240) ===")
    shifts = {0: [], 1: [], 2: []}
    for ax in range(3):
        b0 = betas[0]
        H0 = karlsson_map(*b0)
        k0 = key(H0)
        for n in range(1, 240):
            s = 2 * np.pi * n / 240
            b = list(b0)
            b[ax] += s
            H = karlsson_map(*b)
            if key(H) == k0 and same(H, H0):
                # confirm at a second point
                b1 = list(betas[1])
                b1[ax] += s
                if same(karlsson_map(*b1), karlsson_map(*betas[1])):
                    shifts[ax].append(round(s / np.pi, 4))
        print(f"  axis {ax}: shifts/pi = {shifts[ax]}")

    # 2. candidate point maps (linear in beta, incl. conj/transpose)
    print("=== candidate reflections / conjugations ===")
    cands = []
    for st in (lambda t: -t, lambda t: np.pi - t, lambda t: np.pi + t,
               lambda t: t):
        for sp in (lambda p: -p, lambda p: np.pi - p, lambda p: np.pi + p,
                   lambda p: p):
            for sl in (lambda l: -l, lambda l: np.pi - l,
                       lambda l: np.pi + l, lambda l: l):
                for op in ("id", "conj", "T", "CT"):
                    cands.append((st, sp, sl, op))
    kept = []
    for st, sp, sl, op in cands:
        ok = True
        for b in betas[:3]:
            H = karlsson_map(*b)
            Hm = karlsson_map(st(b[0]), sp(b[1]), sl(b[2]))
            if op in ("conj", "CT"):
                Hm = np.conj(Hm)
            if op in ("T", "CT"):
                Hm = Hm.T
            if not same(H, Hm):
                ok = False
                break
        if ok:
            names = {0: "th", 1: "ph", 2: "la"}
            desc = []
            for i, f in enumerate((st, sp, sl)):
                x = 1.2345
                y = f(x)
                if abs(y - x) < 1e-12:
                    d = names[i]
                elif abs(y + x) < 1e-12:
                    d = f"-{names[i]}"
                elif abs(y - (np.pi - x)) < 1e-12:
                    d = f"pi-{names[i]}"
                else:
                    d = f"pi+{names[i]}"
                desc.append(d)
            kept.append((tuple(desc), op))
            if op != "id" or tuple(desc) != ("th", "ph", "la"):
                print(f"  ({', '.join(desc)}) with {op}")

    # 3. orbit size at a generic point (group generated by finds)
    print("=== orbit size (campaign volume divisor) ===")
    b0 = np.array(betas[3])
    seen = []

    def canon(b):
        return tuple(np.round(np.mod(b, 2 * np.pi), 5))

    frontier = [b0]
    seen.append(canon(b0))
    gens = []
    for ax in range(3):
        for s in shifts[ax]:
            g = np.zeros(3)
            g[ax] = s * np.pi
            gens.append(("shift", g))
    for desc, op in kept:
        gens.append(("map", (desc, op)))
    while frontier:
        b = frontier.pop()
        for kind, g in gens:
            if kind == "shift":
                b2 = b + g
            else:
                desc, _op = g
                b2 = np.array([
                    {"th": b[0], "-th": -b[0], "pi-th": np.pi - b[0],
                     "pi+th": np.pi + b[0]}[desc[0]],
                    {"ph": b[1], "-ph": -b[1], "pi-ph": np.pi - b[1],
                     "pi+ph": np.pi + b[1]}[desc[1]],
                    {"la": b[2], "-la": -b[2], "pi-la": np.pi - b[2],
                     "pi+la": np.pi + b[2]}[desc[2]]])
            c = canon(b2)
            if c not in seen:
                seen.append(c)
                frontier.append(b2)
    print(f"  orbit size (incl. conj/transpose classes): {len(seen)}")
    print(f"  => campaign volume divisor ~ {len(seen)}")


if __name__ == "__main__":
    main()
